{
 "title": "Jormungandr Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Jormungandr Last Block Height",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockHeight > 0",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Jormungandr Last Block Height gained/sec 1h avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(jormungandr_lastBlockHeight[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Jormungandr Last Block Date",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "jormungandr_lastBlockDate > 0", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Jormungandr Last Block Height gained/sec, 5m avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jormungandr_lastBlockHeight[5m])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Jormungandr Transaction Received Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "jormungandr_txRecvCnt", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Jormungandr Blocks Received Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jormungandr_blockRecvCnt", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Jormungandr Last Block Sum",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "jormungandr_lastBlockSum", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Jormungandr Uptime",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "jormungandr_uptime", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Faucet Funds (ADA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jormungandr_address_ca1sk39rfwgf3l4x636r70z7mnw8g7vxkekchn8jl476dx75v4p2tdqq9z8np4_funds / 1e6",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Jormungandr Last Block Fees",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "jormungandr_lastBlockFees", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "TCP Conns",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Jormungandr Last Block Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockTime * 1000",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Faucet Tx Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jormungandr_address_ca1sk39rfwgf3l4x636r70z7mnw8g7vxkekchn8jl476dx75v4p2tdqq9z8np4_counts",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Last Block Hash",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 78 },
   "targets": [
    { "expr": "jormungandr_lastBlockHash" }
   ]
  }
 ]
}